export { default as getTextColor } from "./getTextColor";
export { default as capitalized } from "./capitalized";
export { default as getCurrentTabFromRoute } from "./getCurrentTabFromRoute";
export { default as getCurrentCategoryFromRoute } from "./getCurrentCategoryFromRoute";
export { default as getCurrentGameCategoryFromRoute } from "./getCurrentGameCategoryFromRoute";
export { default as getFormattedDate } from "./getFormattedDate";
export { default as oppositeFormType } from "./oppositeFormType";
export { default as generateNewPlatforms } from "./generateNewPlatforms";
export { default as findPlatformIconFromLabel } from "./findPlatformIconFromLabel";
